### PR TITLE
improve Typescript compatibility

### PR DESCRIPTION
**Pull request by KMahoney**
These small changes make the library compatible with much earlier versions of Typescript.

### CODE REVIEW

**Comment by slvrtrn** [comment]
I'd be happy to merge this if this is required for your use case but I have a few concerns:
- The main one is: how do we verify that the imports are organized in a proper way for future commits if we use only modern versions of TS for the development and CI? I doubt that we want to add an extra matrix run for that.
- What are the blockers for the users to upgrade their TS version?
- Is it possible to set up WebStorm's "optimize imports" feature to comply with the older import syntax?

**Comment by KMahoney** [comment]
There's no need to merge on my behalf. This just solved an immediate problem for me, and I thought it might open up the library to more users.

We (@causalhq) probably will upgrade Typescript soon anyway. Tomorrow I'll check if it's as simple as bumping the number :)

**Comment by slvrtrn** [comment]
@KMahoney yep, please let me know.
If it helps immediately, I will just merge this one and release a new tag with your changeset.
So there will be at least one version that works with the older TS versions.
But it will not be guaranteed that the imports will not be "broken" for the old versions of TS in the future.

**Comment by slvrtrn** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
